### PR TITLE
add needCheckAscii param as second param

### PR DESCRIPTION
**Pull request by GuoSirius**
Users can decide whether to use ASCII or not

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don't understand. Unicode in a non-extended path is not valid.

**Comment by slorber** [comment]
Can you explain these rules @sindresorhus ? Not sure to understand.

I just know that in Docusaurus we use this and get an error when users use a filename with Chinese chars:

`D:\doc\helpcenter\my-website\static\images\4\82\中文.png`

Not sure to understand why this lib would not convert `\\` to `/` ?

**Review by katelynnashley95icloudcom — APPROVED** [review]

**Review by Zbylby — APPROVED** [review]

**Review by swornov — APPROVED** [review]

**Comment by sindresorhus** [comment]
@slorber https://github.com/sindresorhus/slash/commit/d52b47310d2d8a53f2cb15d31ec2e1e717dfc19b#diff-5e7c713ebbfce55b34bc3a5d62c426f40e998d729bdea6f61d302ca0cbf588a2R3-R5 However, this might have been worked around in Node.js or fixed in Windows at some point. So maybe it makes sense to remove the `hasNonAscii` check altogether if anyone can confirm that a path with Unicode still works fine after being converted to forward slashes.

**Review by Vladisvob — APPROVED** [review]

**Review by Vladisvob — APPROVED** [review]

**Comment by Vladisvob** [comment]
#16

**Review by Vladisvob — APPROVED** [review]

**Review by Vladisvob — CHANGES_REQUESTED** [review]
#16

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/slash/releases/tag/v5.0.0

**Pull request closed without merging**
