### PR TITLE
feat: commonjs support

### PR DESCRIPTION
**Pull request by markthree**
This is a perfect commonjs compatible solution

### CODE REVIEW

**Comment by markthree** [comment]
I referenced this library, but there is no support for commonjs, so I mentioned this pr

**Comment by sindresorhus** [comment]
No thanks

**Comment by sindresorhus** [comment]
ESM only is intentional

**Comment by markthree** [comment]
> ESM only is intentional

OK, but it's not user-friendly. For example, I have a require scenario, but I have to migrate it manually

**Pull request closed without merging**
