### PR TITLE
has Chinese characters

### PR DESCRIPTION
**Pull request by xiaohuoni**
fix Naming with Chinese

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please elaborate on what this is. Also read https://msdn.microsoft.com/en-us/library/aa365247.aspx for context.

**Comment by xiaohuoni** [comment]
I'm sorry my English is not good, but I try to explain the problem.
I use `slash` to transform my file path
when the file name has chinese characters,`slash` no work.

when the Naming with Chinese ，use slash has a bug

# code
```js
import { writeFileSync } from 'fs';
import { join } from 'path';
import slash from 'slash';
const dvaContainerPath = join(process.cwd(), 'path.js');
const content = slash(process.cwd());
writeFileSync(dvaContainerPath, JSON.stringify(content), 'utf-8');
```
you can see the product:[中文字符](https://github.com/xiaohuoni/slash-with-Chinese/blob/master/lib/%E4%B8%AD%E6%96%87%E5%AD%97%E7%AC%A6/node/path.js) and [EnglishCharacters](https://github.com/xiaohuoni/slash-with-Chinese/blob/master/lib/englishCharacters/node/path.js)
# Chinese Characters
```js
"e:\\0601\\slash-with-Chinese\\lib\\中文字符\\node"
```

# EnglishCharacters
```js
"e:/0601/slash-with-Chinese/lib/englishCharacters/node"
```
 I new a [Demo](https://github.com/xiaohuoni/slash-with-Chinese),you can run it.

**Comment by linhuiw** [comment]
any update about this PR?

**Comment by sindresorhus** [comment]
Please link to some documentation that proves that your changes are correct. If you don't know any, I would suggest opening an issue instead.

**Comment by xiaohuoni** [comment]
https://github.com/sorrycc/slash2

It works well in [umi](https://github.com/umijs/umi) 、 [ant-design-pro](https://github.com/ant-design/ant-design-pro) and [kiwi](https://github.com/alibaba/kiwi)

**Pull request closed without merging**
