### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by reggi**

### CODE REVIEW

**Comment by sindresorhus** [comment]
No, that's the whole point of this module.

**Comment by reggi** [comment]
Hey @sindresorhus sorry for that. I'm a bit confused. I was under the assumption that this module would take a path in posix format and when on a windows machine convert it.

**Comment by reggi** [comment]
I'm running a test on different operating systems and I'm expecting a path format to come back with posix.

```
Uncaught AssertionError: expected { Object (toCwd, toDst) } to deeply equal { Object (toCwd, toDst) }
      + expected - actual
 
       {
         "toCwd": "foo.txt"
      -  "toDst": "..\\foo.txt"
      +  "toDst": "../foo.txt"
       }
```

Looking for viable solutions if you have any.

**Comment by sindresorhus** [comment]
I have no idea why you would assume that. The repo description couldn't be clearer:

> Convert Windows backslash paths to slash paths: `foo\\bar` ➔ `foo/bar`

**Comment by sindresorhus** [comment]
I don't know what else to say. It's all in the readme.

**Pull request closed without merging**
